### ISSUE TITLE
Fixed issue when fetching from the swift environment the same URL multiple times

### ISSUE THREAD

**Issue by gildas-lormeau** [captaindavepdx/SingleFileMacOS#1]
This issue could happen if multiple frames embed the same resource and if this resource is fetched from the swift environment. In this case, the SingleFile code would remain blocked during processing. Here is below the content of your `content-fetch-resource.js` to fix it. I was not able to find the actual content in your project on GitHub by the way.

	this.singlefile.lib.fetch.content.resources = this.singlefile.lib.fetch.content.resources || (() => {

		const pendingMessages = new Map();

		return {
			fetch: async url => {
				try {
					let response = await fetch(url, { cache: "force-cache" });
					if (response.status == 403) {
						response = nativeFetch(url);
					}
					return response;
				}
				catch (error) {
					return nativeFetch(url);
				}
			},
			callbackFetch: message => {
				const callbacks = pendingMessages.get(message.url);
				if (callbacks) {
					pendingMessages.delete(message.url);
					if (message.error) {
						callbacks.forEach(callback => callback.reject(message.error));
					} else {
						const data = {
							status: message.status,
							headers: { get: name => message.headers[name] },
							arrayBuffer: async () => new Uint8Array(message.body).buffer
						};
						callbacks.forEach(callback => callback.resolve(data));
					}
				}
			}
		};

		function nativeFetch(url) {
			return new Promise((resolve, reject) => {
				webkit.messageHandlers.performHttpRequest.postMessage(url);
				let callbacks = pendingMessages.get(url);
				if (!callbacks) {
					callbacks = [];
					pendingMessages.set(url, callbacks);
				}
				callbacks.push({ resolve, reject });
			});
		}

	})();

**Comment by captaindavepdx** [comment]
Hi @gildas-lormeau ,

Made the changes, thanks for the update! 

And, that's correct. The actual content is stored on the user's computer. 

The MacOS application converts the "SingleFile-master" folder into 3 JavaScript files.

[Demo](https://www.dropbox.com/s/p8kt87xqwykhpc7/Demo.mov?dl=0)

**Comment by gildas-lormeau** [comment]
Doesn't that mean that nobody can run your project out of the box by building it on its machine?

**Comment by captaindavepdx** [comment]
The GitHub clone contains the working files of the MacOS application. Typically, they'd clone the repository, open it in XCode, and then run the application in the Simulator. If they wanted to export it as an executable application, they can do that in XCode. And, that's normal for Swift projects. 

In that case, they'd still need to unpackage the `SingleFile-master.zip`, and then use the MacOS application that's running in the XCode Simulator to convert it.

But, that's why I linked the executable application, and the SingleFile-master file. I set it up like that to extend its usability. If you make a minor change, then they can just convert the latest version of SingleFile, instead of having to update the code themselves. 

But, they'd still have to update it themselves for changes that affect the custom code you wrote for the MacOS application.

Do you think it'd be better to hard code the SingleFile code into the MacOS application?

<img width="938" alt="Screen Shot 2019-08-05 at 12 26 13 PM" src="https://user-images.githubusercontent.com/30560737/62489942-f671ed80-b77c-11e9-9d8e-771457671c8e.png">

**Comment by gildas-lormeau** [comment]
As i said, I wished the steps 1 to 7 would be handled transparently by the swift application itself (cf. https://github.com/gildas-lormeau/SingleFile/issues/231#issuecomment-517207210). 

As someone who doesn't own a Mac, I wished also I could browse your repository and be able to find *all* the source code. I think indeed the JS script I posted in this issue should be "hardcoded" in your application since it's specific to it.

**Comment by captaindavepdx** [comment]
I must have missed something. All the conversions are publicly visible and hardcoded [Here](https://github.com/captaindavepdx/SingleFileMacOS/blob/master/SingleFile/Controller/FileViewController.swift). Isn't that transparent?

The application automates the conversion process. But, doesn't the user need to tell the it which files to convert, where to save the converted files, and click a button to start the conversion?

I suppose I could have the MacOS application set itself when it's opened for the first time. It'd display a loading image while it downloads and converts your repository in the background? That way from the users point of view, steps 1 to 7 never happened? 

Is that what you mean? Or, could you please clarify?

I can structure it however, check out the link, and let me know what changes we should make. =]

**Comment by gildas-lormeau** [comment]
Sorry, I was not finding where the script was hardcoded. That's okay for me. It would be better if this code was in a "lib" or "business" directory in your project IMHO and not in a Controller. 

I would also recommend you to import SingleFile code as a submodule, cf. https://github.blog/2016-02-01-working-with-submodules/. It would make things easier for you and people who would want to clone your project. Finally, I think it would be better if the conversion was done automatically when your application starts. These recommendations won't remove all the steps but they will help to make your project easier to use.

**Comment by captaindavepdx** [comment]
Cool, will look into that, and make changes accordingly, thanks @gildas-lormeau ! =]

**Comment by captaindavepdx** [comment]
Hi @gildas-lormeau ! Ok, so I've separated the code for the `Single File` and `JavaScript` conversions. And, I've cleaned up the code and simplified the functions a bit. [[SingleFile.swift](https://pastebin.com/TV8gzuFr)] [[JavaScript.swift](https://pastebin.com/ntU9SE4A)]

Next, I'll look into converting it into a Swift framework. Thought it would be pretty cool if people could just import `SingleFile` directly into their Swift projects. =]

**Comment by gildas-lormeau** [comment]
Hi @captaindavepdx. Yes, that's what I had in mind. I think you should not try to convert `content-fetch-resources.js` though. Just copy the content of your script file somewhere in your project in a js file and append its content to other "converted" files. I think that importing SingleFile as library would be indeed pretty cool :).
